kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
  - role: worker
    extraPortMappings:
      - containerPort: 30000
        hostPort: 8181
        listenAddress: 127.0.0.1
        protocol: TCP
      - containerPort: 30001
        hostPort: 8484
        listenAddress: 127.0.0.1
        protocol: TCP
  - role: worker
