kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8soperators
subjects:
  - kind: ServiceAccount
    name: k8soperators
    namespace: default
roleRef:
  kind: ClusterRole
  name: k8soperators
  apiGroup: rbac.authorization.k8s.io
