apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8soperators
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8soperator-cr-admin
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
rules:
  - apiGroups:
      - k8soperators.pliu.github.com
    resources:
      - '*'
    verbs:
      - '*'
