apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8soperators
rules:
  - apiGroups:
      - k8soperators.pliu.github.com
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups:
      - '*'
    resources:
      - namespaces
    verbs:
      - '*'
  - apiGroups:
      - '*'
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'
