apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: k8soperators
rules:
  - apiGroups:
      - '*'
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - '*'
    resources:
      - configmaps
    verbs:
      - '*'
  - apiGroups:
      - 'bitnami.com'
    resources:
      - '*'
    verbs:
      - '*'
