apiVersion: v1
kind: Service
metadata:
  name: operator-server
spec:
  ports:
    - name: http
      nodePort: 30000
      port: 8080
      protocol: TCP
  selector:
    name: k8soperators
  type: NodePort
