apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8soperators
spec:
  replicas: 1
  selector:
    matchLabels:
      name: k8soperators
  template:
    metadata:
      labels:
        name: k8soperators
    spec:
      serviceAccountName: k8soperators
      containers:
        - name: k8soperators
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
            - k8soperators
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_NAME
              value: "k8soperators"
